- name: Azure(Ubuntu) FVCOM
  hosts: all
  
  gather_facts: true
  tasks:
  - name: Add user hpc
    become: yes
    user:
      name: hpc
      shell: /bin/bash

  - name: Set SSH key
    become: yes
    authorized_key:
      user: hpc
      state: present
      key: "{{ lookup('file', '~/hpc.key.pub') }}"

  - name: Distribute private keyfiles to hosts
    become: yes
    become_user: hpc
    copy: 
      src: "~/hpc.key"
      dest: "/home/hpc/.ssh/id_dsa" 
      mode: 0600

  - name: Add hpc to sudoers
    become: yes
    copy:
      dest: "/etc/sudoers.d/devops"
      content: "hpc  ALL=(ALL)  NOPASSWD: ALL"

  - name: Disable host SSH key checking
    become: yes
    become_user: hpc
    copy:
      dest: "~/.ssh/config"
      content: "Host *\n    StrictHostKeyChecking no\n"

  - name: Create MPI Hosts file
    become: yes
    become_user: hpc
    copy:
      dest: "~/hosts"
      content: "{{ groups['all'] | map('extract', hostvars, ['ansible_default_ipv4', 'address']) | join('\n') }}"

  - name: Add PKEY to environment
    become: yes
    become_user: hpc
    shell: |
      high_key=`sort -r /sys/class/infiniband/mlx5_0/ports/1/pkeys/* | head -1`
      modified_key=$(printf '0x%04X\n' "$((high_key ^ 0x8000))")
      echo "UCX_IB_PKEY=$modified_key" | sudo tee -a /etc/environment
 
  - name: Download FVCOM dataset
    become: yes
    become_user: hpc
    shell: |
      azcopy copy "{{ lookup('env','SAS_FVCOM_DATA') }}" /opt --recursive=true
    args:
      creates: /opt/data

  - name: Do science
    become: yes
    become_user: hpc
    run_once: true
    shell: |
      high_key=`sort -r /sys/class/infiniband/mlx5_0/ports/1/pkeys/* | head -1`
      modified_key=$(printf '0x%04X\n' "$((high_key ^ 0x8000))")
      export UCX_IB_PKEY=$modified_key

      cd /opt/data/wvi_inlets4
      # mpirun -npernode `nproc` -mca pml ucx --mca btl ^vader,tcp,openib --hostfile ~/hosts fvcom --CASENAME=wvi_inlets4
      
      
      
      
      # SINGLE HOST TEST
      # mpirun --bind-to core --camca btl self,vader ./fvcom --CASENAME=wvi_inlets4

      # Benchmark sendrecv over UCX/IB
      # mpirun -npernode 44 -mca pml ucx --mca btl ^vader,tcp,openib --hostfile ~/hosts IMB-MPI1 sendrecv

      # Try FVCOM over UCX/IB
      # mpirun -npernode 44 -mca pml ucx --mca btl ^vader,tcp,openib --hostfile ~/hosts -x UCX_IB_PKEY=$UCX_IB_PKEY ./fvcom --CASENAME=wvi_inlets4
      # mpirun -npernode 44 -mca pml ucx --mca btl ^vader,tcp,openib --hostfile ~/hosts fvcom --CASENAME=wvi_inlets4
      
      # Pingpong over UCX/IB
      # mpirun -npernode 44 -mca pml ucx --mca btl ^vader,tcp,openib --hostfile ~/hosts -x UCX_IB_PKEY=$UCX_IB_PKEY IMB-MPI1 pingpong

      # 0.0336  132 cores   = 0.00025454545 per core - 3928.57142857
      # 0.0496  88 cores    = 0.00056363636 - 1774.19354839
