- name: Azure(Ubuntu) FVCOM
  hosts: all
  
  gather_facts: true
  tasks:
  - name: Add user hpc
    become: yes
    user:
      name: hpc
      shell: /bin/bash

  - name: Set SSH key
    become: yes
    authorized_key:
      user: hpc
      state: present
      key: "{{ lookup('file', '~/hpc.key.pub') }}"

  - name: Distribute private keyfiles to hosts
    become: yes
    become_user: hpc
    copy: 
      src: "~/hpc.key"
      dest: "/home/hpc/.ssh/id_dsa" 
      mode: 0600

  - name: Add hpc to sudoers
    become: yes
    copy:
      dest: "/etc/sudoers.d/devops"
      content: "hpc  ALL=(ALL)  NOPASSWD: ALL"

  - name: Disable host SSH key checking
    become: yes
    become_user: hpc
    copy:
      dest: "~/.ssh/config"
      content: "Host *\n    StrictHostKeyChecking no\n"

  - name: Create MPI Hosts file
    become: yes
    become_user: hpc
    copy:
      dest: "~/hosts"
      content: "{{ groups['all'] | map('extract', hostvars, ['ansible_default_ipv4', 'address']) | join('\n') }}"

  - name: Add PKEY to environment
    become: yes
    become_user: hpc
    shell: |
      high_key=`sort -r /sys/class/infiniband/mlx5_0/ports/1/pkeys/* | head -1`
      modified_key=$(printf '0x%04X\n' "$((high_key ^ 0x8000))")
      echo "UCX_IB_PKEY=$modified_key" | sudo tee -a /etc/environment
 
  - name: Download FVCOM dataset
    become: yes
    become_user: hpc
    shell: |
      azcopy copy "{{ lookup('env','SAS_FVCOM_DATA') }}" /opt --recursive=true
    args:
      creates: /opt/data

  - name: Set Timezone
    become: yes
    shell: sudo timedatectl set-timezone America/Toronto


  - name: Master node
    become: yes
    become_user: hpc
    run_once: true
    shell: uname

  - name: Do science
    become: yes
    become_user: hpc
    run_once: true
    shell: |
      high_key=`sort -r /sys/class/infiniband/mlx5_0/ports/1/pkeys/* | head -1`
      modified_key=$(printf '0x%04X\n' "$((high_key ^ 0x8000))")
      export UCX_IB_PKEY=$modified_key

      # WVI_INLETS4
      # sudo mkdir /mnt/output
      # sudo chmod 777 -R /mnt
      # cd /opt/data/wvi_inlets4
      # mpirun -npernode `nproc` -mca pml ucx --mca btl ^vader,tcp,openib --hostfile ~/hosts fvcom_wvi_inlets4_heating --CASENAME=wvi_inlets4 | tee -a /mnt/output/output.txt
      
      # ESI
      sudo mkdir /mnt/output
      sudo chmod 777 -R /mnt
      cd /opt/data/esi
      
      echo "Start time `date`" | tee -a /mnt/output/output.txt
      mpirun -npernode `nproc` -mca pml ucx --mca btl ^vader,tcp,openib --hostfile ~/hosts fvcom_esi_tide --CASENAME=esi 2>&1 | tee -a /mnt/output/output.txt
      echo "End time `date`" | tee -a /mnt/output/output.txt
      azcopy copy /mnt/output "{{ lookup('env','SAS_FVCOM_OUTPUT') }}" --recursive=true
      echo "Upload end time `date`" | tee -a /mnt/output/output.txt

