- name: Azure(Ubuntu) FVCOM
  hosts: all
  
  gather_facts: true
  tasks:
  - name: Add user hpc
    become: yes
    user:
      name: hpc
      shell: /bin/bash

  - name: Set SSH key
    become: yes
    authorized_key:
      user: hpc
      state: present
      key: "{{ lookup('file', '~/hpc.key.pub') }}"

  - name: Distribute private keyfiles to hosts
    become: yes
    become_user: hpc
    copy: 
      src: "~/hpc.key"
      dest: "/home/hpc/.ssh/id_dsa" 
      mode: 0600

  - name: Add hpc to sudoers
    become: yes
    copy:
      dest: "/etc/sudoers.d/devops"
      content: "hpc  ALL=(ALL)  NOPASSWD: ALL"

  - name: Disable host SSH key checking
    become: yes
    become_user: hpc
    copy:
      dest: "~/.ssh/config"
      content: "Host *\n    StrictHostKeyChecking no\n"

  - name: Azure specific UCX/IB
    script: set-pkey.sh

  - name: Create MPI Hosts file
    become: yes
    become_user: hpc
    copy:
      dest: "~/hosts"
      content: "{{ groups['all'] | map('extract', hostvars, ['ansible_default_ipv4', 'address']) | join('\n') }}"

  - name: Change limits.conf for InfiniBand
    become: yes
    become_user: hpc
    shell: |
      cd
      chmod -R
      cat << EOF | sudo tee -a /etc/security/limits.conf
      *               hard    memlock         unlimited
      *               soft    memlock         unlimited
      *               hard    nofile          65535
      *               soft    nofile          65535
      EOF

  - name: Tune Network
    become: yes
    become_user: hpc
    shell: |
      sysctl -w net.core.rmem_max=2147483647
      sysctl -w net.core.wmem_max=2147483647
      sysctl -w net.ipv4.tcp_rmem=4096 87380 2147483647
      sysctl -w net.ipv4.tcp_wmem=4096 65536 2147483647
      #sysctl -w net.core.netdev_max_backlog=30000
      sysctl -w net.core.rmem_default=16777216
      sysctl -w net.core.wmem_default=16777216
      sysctl -w net.ipv4.tcp_mem='16777216 16777216 16777216'
      sysctl -w net.ipv4.route.flush=1

  - name: Download blob
    become: yes
    become_user: hpc
    shell: 'azcopy copy "{{ lookup("env","SAS_URL") }}" ~/ --recursive=true'
    args:
      creates: ~/fvcom

  - name: Compile
    become: yes
    become_user: hpc
    shell: |
      cd
      chmod -R 755 fvcom
      sudo chmod 777 -R ~/fvcom
      sudo mkdir /mnt &> /dev/null
      sudo mkdir /mnt/fvcom &> /dev/null
      sudo chmod 777 -R /mnt/fvcom &> /dev/null
      sudo chmod 777 -R /mnt
      cd fvcom/FVCOM41/Configure/
      ./setup -a UBUNTU-18.04-GCC -c wvi_inlets4_heating

      make clean
      make libs -j
      make gotm -j
      make fvcom -j
      make -j
      cd
      cp fvcom/FVCOM41/FVCOM_source/fvcom fvcom/_run
      

    args:
      creates: ~/fvcom/_run/fvcom

  - name: Do science
    become: yes
    become_user: hpc
    run_once: true
    shell: |
      cd
      cd fvcom/_run

      # SINGLE HOST TEST
      # mpirun --bind-to core --mca btl self,vader ./fvcom --CASENAME=wvi_inlets4

      # Benchmark sendrecv over UCX/IB
      # mpirun -npernode 44 -mca pml ucx --mca btl ^vader,tcp,openib -x UCX_IB_PKEY=$UCX_IB_PKEY --hostfile ~/hosts IMB-MPI1 sendrecv

      # Try FVCOM over UCX/IB
      # mpirun -npernode 44 -mca pml ucx --mca btl ^vader,tcp,openib -x UCX_IB_PKEY=$UCX_IB_PKEY --hostfile ~/hosts ./fvcom --CASENAME=wvi_inlets4