- name: Optional DPDK installation
  hosts: all
  gather_facts: true
  tasks:
  - name: Install packages for compilation
    become: yes
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - librdmacm-dev 
      - librdmacm1 
      - build-essential 
      - libnuma-dev 
      - libmnl-dev

  - name: DPDK Files
    become: yes
    unarchive:
      src: https://fast.dpdk.org/rel/dpdk-18.05.1.tar.xz
      dest: ~/
      remote_src: yes

  - name: Compile DPDK
    become: yes
    shell: |
      cd /root/dpdk-stable-18.05.1
      make config T=x86_64-native-linuxapp-gcc
      sed -ri 's,(MLX._PMD=)n,\1y,' build/.config
      make -j
      sudo make install

  - name: DPDK Config
    become: yes
    shell: |
      echo 1024 | sudo tee /sys/devices/system/node/node*/hugepages/hugepages-2048kB/nr_hugepages  
      mkdir /mnt/huge
      mount -t hugetlbfs nodev /mnt/huge
