- name: Setup base hpc
  hosts: all
  gather_facts: true
  tasks:
  - name: Add user hpc
    become: yes
    user:
      name: hpc
      shell: /bin/bash

  - name: Set SSH key
    become: yes
    authorized_key:
      user: hpc
      state: present
      key: "{{ lookup('file', '~/hpc.key.pub') }}"

  - name: Distribute private keyfiles to hosts
    become: yes
    become_user: hpc
    copy: 
      src: "~/hpc.key"
      dest: "/home/hpc/.ssh/id_dsa" 
      mode: 0600

  - name: Add hpc to sudoers
    become: yes
    copy:
      dest: "/etc/sudoers.d/devops"
      content: "hpc  ALL=(ALL)  NOPASSWD: ALL"

  - name: Disable host SSH key checking
    become: yes
    become_user: hpc
    copy:
      dest: "~/.ssh/config"
      content: "Host *\n    StrictHostKeyChecking no\n"

  - name: Install packages for compilation
    become: yes
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - cmake
      - git
      - makedepf90
      - gfortran
      - gcc
      - libnetcdf-dev
      - libnetcdff-dev
      - netcdf-bin
      - openmpi-bin
      - openmpi-common
      - libopenmpi-dev
      - libhdf5-openmpi-dev
      - patch
      - htop
      - iptraf-ng

    
  - name: Install azcopy to /usr/bin
    become: yes
    unarchive:
      src: https://aka.ms/downloadazcopy-v10-linux
      dest: /usr/bin
      creates: /usr/bin/azcopy
      remote_src: yes
      extra_opts: [--strip-components=1]
    retries: 3

  - name: Download blob
    become: yes
    become_user: hpc
    shell: 'azcopy copy "{{ lookup("env","SAS_URL") }}" ~/ --recursive=true'
    args:
      creates: ~/fvcom

  - name: Create MPI Hosts file
    become: yes
    become_user: hpc
    copy:
      dest: "~/hosts"
      content: "{{ groups['all'] | map('extract', hostvars, ['ansible_eth0', 'ipv4', 'address']) | join('\n') }}"

  - name: Compile
    become: yes
    become_user: hpc
    shell: |
      cd
      chmod -R 755 fvcom
      sudo mkdir /mnt/fvcom &> /dev/null
      sudo chmod 777 /mnt/fvcom &> /dev/null
      cd fvcom/FVCOM41/Configure/
      ./setup -a UBUNTU-16.04-GCC -c wvi_inlets4_heating

      make clean
      make libs gotm fvcom -j $(($(nproc)-1))
      make -j $(($(nproc)-1))
      cd
      cp fvcom/FVCOM41/FVCOM_source/fvcom fvcom/_run

      sudo chmod 777 /mnt
      # Create the output directory
      mkdir /mnt/fvcom
      cd
      git clone https://github.com/intel/opa-mpi-apps/
      cd opa-mpi-apps/MpiApps/apps/imb/src
      make CC=mpicc
      cp IMB-MPI1 ~/fvcom/_run
    args:
      creates: ~/fvcom/_run/fvcom

  - name: update openib parameter file
    become: yes
    lineinfile:
      path: /usr/share/openmpi/mca-btl-openib-device-params.ini
      regexp: '^vendor_part_id = 4119,4121'
      line: 'vendor_part_id = 4119,4120,4121'

  - name: Tune Network
    become: yes
    become_user: hpc
    shell: |
      sysctl -w net.core.rmem_max=16777216
      sysctl -w net.core.wmem_max=16777216
      sysctl -w net.ipv4.tcp_rmem=4096 87380 16777216
      sysctl -w net.ipv4.tcp_wmem=4096 65536 16777216
      sysctl -w net.core.netdev_max_backlog=30000
      sysctl -w net.core.rmem_default=16777216
      sysctl -w net.core.wmem_default=16777216
      sysctl -w net.ipv4.tcp_mem='16777216 16777216 16777216'
      sysctl -w net.ipv4.route.flush=1

  - name: Do science
    become: yes
    become_user: hpc
    run_once: true
    shell: |
      cd
      cd fvcom/_run
      
      #echo "{{ groups['all'] | map('extract', hostvars, ['ansible_eth0', 'ipv4', 'address']) | join(',') }}" > /mnt/fvcom/hostsline
      #nohup mpirun -npernode `nproc` -hosts {{ groups['all'] | map('extract', hostvars, ['ansible_eth0', 'ipv4', 'address']) | join(',') }} ./fvcom --CASENAME=wvi_inlets4 > /mnt/fvcom/stdout.txt 2> /mnt/fvcom/stderr.txt &
      #mpirun -ppn `npernode` -hosts {{ groups['all'] | map('extract', hostvars, ['ansible_eth0', 'ipv4', 'address']) | join(',') }} ./fvcom --CASENAME=wvi_inlets4 > /mnt/fvcom/stdout.txt 2> /mnt/fvcom/stderr.txt
      #azcopy copy /mnt/fvcom \"{{ lookup('env','SAS_URL') }}\" --recursive
      # mpitune took 30 minutes. can tune the message sizes perhaps to trim it down, but best
      # to save this
      #mpitune --ppn-range 16 -hf hosts -fl shm:dapl -hr 2
      #mpirun --mca btl self,tcp ./fvcom --CASENAME=wvi_inlets4
      
      ## Y-nodes using host file, using only physical cores
      # mpirun -N $(($(nproc)/2)) --hostfile ~/hosts --mca btl self,vader,tcp ./fvcom --CASENAME=wvi_inlets4
      
      # Bind options
      # --bind-to numa
      # --bind-to core
      # --bind-to socket
      
      # f16 - scaling is perfect with 1node vs 2node. --oversubscribe helps a little bit, not much.
      
      # mpirun -N 32 --mca btl self,vader,tcp ./fvcom --CASENAME=wvi_inlets4
      # mpirun -N $(($(nproc)/2)) --hostfile ~/hosts --mca btl self,vader,tcp ./fvcom --CASENAME=wvi_inlets4


      # 8 nodes, f64
      # no parameters, 0.06
      # bind to NUMA, 0.058
      # bind to CORE, 0.61
      # bind to SOCKET , 0.61

      # 2 nodes, f72
      # no params, 0.072
      # bind to NUMA, 0.072